// 底稿系统
const manuscriptResources = [
  {
    id: 137,
    code: 'projectManagement',
    name: '底稿项目管理',
    title: '底稿项目管理',
    children: [
      {
        id: 137001,
        code: 'informationManagement',
        path: 'projectManagement/informationManagement',
        name: '项目信息管理',
        title: '项目信息管理',
        icon: '',
        href: '',
        description: '',
        actions: [
          // {
          //   id: 137001001,
          //   code: 'informationManagement:query',
          //   name: '项目信息管理列表查询',
          //   method: 'POST',
          //   type: 'btn',
          //   description: '项目信息管理列表查询',
          //   uri: '/product/getProductPage',
          //   uriFlag: '/yss-awp-server',
          // },
          {
            id: 137001002,
            code: 'informationManagement:add',
            name: '新建项目',
            method: 'POST',
            type: 'btn',
            description: '项目信息管理新建项目',
            uri: '/product/addProduct',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137001003,
            code: 'informationManagement:look',
            name: '查看',
            method: 'POST',
            type: 'btn',
            description: '项目信息管理查看',
            uri: '/product/updateProductNew',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137001004,
            code: 'informationManagement:deCheck',
            name: '反审核',
            method: 'POST',
            type: 'btn',
            description: '项目信息管理反审核',
            uri: '/product/batchCheckProduct',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137001005,
            code: 'informationManagement:update',
            name: '修改',
            method: 'POST',
            type: 'btn',
            description: '项目信息管理修改',
            uri: '/product/updateProductNew',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137001006,
            code: 'informationManagement:Check',
            name: '审核',
            method: 'POST',
            type: 'btn',
            description: '项目信息管理审核',
            uri: '/product/batchCheckProduct',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137001007,
            code: 'informationManagement:delete',
            name: '删除',
            method: 'POST',
            type: 'btn',
            description: '项目信息管理删除',
            uri: '/product/batchDeleteProduct',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137001008,
            code: 'informationManagement:stop',
            name: '终止',
            method: 'POST',
            type: 'btn',
            description: '项目信息管理项目终止',
            uri: '/product/terminationProduct',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137001009,
            code: 'informationManagement:issue',
            name: '发行',
            method: 'POST',
            type: 'btn',
            description: '项目信息管理项目发行',
            uri: '/product/productPublish',
            uriFlag: '/yss-awp-server',
          },
          // {
          //   id: 137001014,
          //   code: 'informationManagement:saveUrl',
          //   name: '新建项目保存',
          //   method: 'POST',
          //   type: 'uri',
          //   description: '新建项目保存',
          //   uri: '/product/addProduct',
          //   uriFlag: '/yss-awp-server',
          // },
          {
            id: 137001015,
            code: 'informationManagement:apply',
            name: '申报',
            method: 'POST',
            type: 'btn',
            description: '项目信息管理申报',
            uri: '/product/projectReport',
            uriFlag: '/yss-awp-server',
          },
        ],
      },
      // {
      //   id: 137002,
      //   code: 'taskManagement',
      //   path: 'projectManagement/taskManagement',
      //   name: '项目任务管理_old',
      //   title: '项目任务管理_old',
      //   icon: '',
      //   href: '',
      //   description: '',
      //   actions: [
      //     // {
      //     //   id: 137002001,
      //     //   code: 'taskManagement:test',
      //     //   name: '项目任务管理:测试',
      //     //   method: 'POST',
      //     //   type: 'btn',
      //     //   description: '项目任务管理:测试',
      //     //   uri: '',
      //     //   uriFlag: '',
      //     // },
      //     {
      //       id: 137002001,
      //       code: 'taskManagement:queryApi',
      //       name: '项目任务管理列表查询',
      //       method: 'POST',
      //       type: 'btn',
      //       description: '项目任务管理列表查询',
      //       uri: '/awp/task/list',
      //       uriFlag: '/yss-awp-server',
      //     },
      //     {
      //       id: 137002002,
      //       code: 'taskManagement:commitApi',
      //       name: '项目任务管理提交接口',
      //       method: 'POST',
      //       type: 'btn',
      //       description: '项目任务管理提交接口',
      //       uri: '/awp/task/commit',
      //       uriFlag: '/yss-awp-server',
      //     },
      //     {
      //       id: 137002003,
      //       code: 'taskManagement:commitBtn',
      //       name: '项目任务管理提交按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务管理提交按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //     {
      //       id: 137002004,
      //       code: 'taskManagement:viewBtn',
      //       name: '项目任务管理查看按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务管理查看按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //     {
      //       id: 137002005,
      //       code: 'taskManagement:editBtn',
      //       name: '项目任务管理修改按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务管理修改按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //     {
      //       id: 137002006,
      //       code: 'taskManagement:deleteBtn',
      //       name: '项目任务管理删除按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务管理删除按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //     {
      //       id: 137002007,
      //       code: 'taskManagement:handleBtn',
      //       name: '项目任务管理办理按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务管理办理按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //     {
      //       id: 137002008,
      //       code: 'taskManagement:overBtn',
      //       name: '项目任务管理任务完成按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务管理任务完成按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //     {
      //       id: 137002009,
      //       code: 'taskManagement:commitListApi',
      //       name: '项目任务管理列表提交接口',
      //       method: 'POST',
      //       type: 'btn',
      //       description: '项目任务管理列表提交接口',
      //       uri: '/yss-awp-server',
      //       uriFlag: '/awp/task/commitById',
      //     },
      //     {
      //       id: 137002010,
      //       code: 'taskManagement:commitListBtn',
      //       name: '项目任务管理列表提交按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务管理列表提交按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //     {
      //       id: 137002011,
      //       code: 'taskManagement:creatBtn',
      //       name: '项目任务发起按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务发起按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //     {
      //       id: 137002012,
      //       code: 'taskManagement:treeSaveBtn',
      //       name: '项目任务办理目录树页面保存按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务办理目录树页面保存按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //     {
      //       id: 137002013,
      //       code: 'taskManagement:treeSubBtn',
      //       name: '项目任务办理目录树页面提交按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务办理目录树页面提交按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //     {
      //       id: 137002014,
      //       code: 'taskManagement:treeCancelBtn',
      //       name: '项目任务办理目录树页面取消按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务办理目录树页面取消按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //     {
      //       id: 137002015,
      //       code: 'taskManagement:chiDownLoadBtn',
      //       name: '项目任务二级列表下载按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务办理目录树页面取消按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //     {
      //       id: 137002016,
      //       code: 'taskManagement:chiViewBtn',
      //       name: '项目任务二级列表查看按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务办理目录树页面取消按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //     {
      //       id: 137002017,
      //       code: 'taskManagement:chiExamineBtn',
      //       name: '项目任务二级列表审核按钮',
      //       method: 'POST',
      //       type: 'uri',
      //       description: '项目任务办理目录树页面取消按钮',
      //       uri: '',
      //       uriFlag: '',
      //     },
      //   ],
      // },
      {
        id: 137003,
        code: 'terminationManagement',
        path: 'projectManagement/terminationManagement',
        name: '项目终止管理',
        title: '项目终止管理',
        icon: '',
        href: '',
        description: '',
        actions: [
          {
            id: 137003001,
            code: 'terminationManagement:query',
            name: '列表查询',
            method: 'POST',
            type: 'btn',
            description: '项目终止管理列表查询',
            uri: '/datadict/queryInfo',
            uriFlag: '/ams-base-parameter',
          },
          {
            id: 137001002,
            code: 'terminationManagement:look',
            name: '查看',
            method: 'POST',
            type: 'uri',
            description: '项目终止管理查看',
            uri: '/termination/getDetail',
            uriFlag: '/yss-awp-server',
          },
        ],
      },
      {
        id: 137004,
        code: 'documentManagement',
        path: 'projectManagement/documentManagement',
        name: '项目文档管理',
        title: '项目文档管理',
        icon: '',
        href: '',
        description: '',
        actions: [
          {
            id: 137004001,
            code: 'documentManagement:link',
            name: '查看',
            method: 'POST',
            type: 'btn',
            description: '查看',
            uri: '/productFile/getFileDetailList',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137004002,
            code: 'documentManagement:tabProject',
            name: '项目底稿',
            method: 'POST',
            type: 'btn',
            description: '项目底稿',
            uri: '/productFile/getFilePageChecked',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137004003,
            code: 'documentManagement:tabSeries',
            name: '系列底稿',
            method: 'POST',
            type: 'btn',
            description: '项目底稿',
            uri: '/productFile/getFilePageChecked',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137004004,
            code: 'documentManagement:taskUploadPrinting',
            name: '用印文件归档',
            method: 'POST',
            type: 'btn',
            description: '用印文件归档',
            uri: '/awp/uploadUseSealFile',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137004005,
            code: 'documentManagement:detailUpdateFile',
            name: '更新',
            method: 'POST',
            type: 'btn',
            description: '更新',
            uri: '/awp/updateUseSealFile',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137004007,
            code: 'documentManagement:updateHandle',
            name: '更新',
            method: 'POST',
            type: 'btn',
            description: '更新',
            uri: '/task/fileUpdate/updateHandle',
            uriFlag: '/yss-awp-server',
          },
        ],
      },
      {
        id: 137005,
        code: 'archiveTaskHandleList',
        path: 'projectManagement/archiveTaskHandleList/index',
        name: '项目任务管理',
        title: '项目任务管理',
        icon: '',
        href: '',
        description: '',
        actions: [
          {
            id: 137005001,
            code: 'archiveTaskHandleList:submit',
            name: '提交',
            method: 'POST',
            type: 'btn',
            description: '提交',
            uri: '/awp/task/commitById',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005002,
            code: 'archiveTaskHandleList:link',
            name: '查看',
            method: 'POST',
            type: 'btn',
            description: '查看',
            uri: '/awp/task/info',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005003,
            code: 'archiveTaskHandleList:delete',
            name: '删除',
            method: 'POST',
            type: 'btn',
            description: '删除',
            uri: '/awp/task/delete/batch',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005004,
            code: 'archiveTaskHandleList:execute',
            name: '办理',
            method: 'POST',
            type: 'btn',
            description: '办理',
            uri: '/productFile/getFileDetailList',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005005,
            code: 'archiveTaskHandleList:download',
            name: '下载',
            method: 'POST',
            type: 'btn',
            description: '下载',
            uri: '/path/downloadFile',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005006,
            code: 'archiveTaskHandleList:taskCompleted',
            name: '任务完成',
            method: 'GET',
            type: 'btn',
            description: '任务完成',
            uri: '/awp/task/conventionalEnd',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005007,
            code: 'archiveTaskHandleList:preview',
            name: '预览',
            method: 'POST',
            type: 'btn',
            description: '预览',
            uri: '/fileServer/downloadUploadFile',
            uriFlag: '/ams-file-service',
          },
          {
            id: 137005008,
            code: 'archiveTaskHandleList:check',
            name: '审批（审核页面）',
            method: 'POST',
            type: 'btn',
            description: '审批（审核页面）',
            uri: '/awp/task/process/audit',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005009,
            code: 'archiveTaskHandleList:reviewOpinion',
            name: '审核意见',
            method: 'POST',
            type: 'btn',
            description: '审核意见',
            uri: '/awp/task/process/getOpinion',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005010,
            code: 'archiveTaskHandleList:taskRevoke',
            name: '任务撤销',
            method: 'POST',
            type: 'btn',
            description: '任务撤销',
            uri: '/awp/task/taskRevoke',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005011,
            code: 'archiveTaskHandleList:taskUploadPrinting',
            name: '用印文件归档',
            method: 'POST',
            type: 'btn',
            description: '用印文件归档',
            uri: '/awp/uploadUseSealFile',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005012,
            code: 'archiveTaskHandleList:fileRevoke',
            name: '文件撤销',
            method: 'POST',
            type: 'btn',
            description: '文件撤销',
            uri: '/awp/task/process/fileRevoke',
            uriFlag: '/yss-awp-server',
          },
          // {
          //   id: 137005013,
          //   code: 'taskManagementStart:commit',
          //   name: '发起任务修改任务:提交',
          //   method: 'POST',
          //   type: 'btn',
          //   description: '发起任务修改任务:提交',
          //   uri: '/awp/task/commit',
          //   uriFlag: '/yss-awp-server',
          // },
          {
            id: 137005014,
            code: 'archiveTaskHandleList:edit',
            name: '编辑',
            method: 'POST',
            type: 'btn',
            description: '编辑',
            uri: '/awp/task/save',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005015,
            code: 'archiveTaskHandleList:initiateTask',
            name: '发起任务',
            method: 'POST',
            type: 'btn',
            description: '发起任务',
            uri: '/awp/task/save',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005016,
            code: 'archiveTaskHandleList:handleDelete',
            name: '删除（办理页面）',
            method: 'POST',
            type: 'btn',
            description: '删除（办理页面）',
            uri: '/awp/task/process/uploadFileRevoke',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005017,
            code: 'archiveTaskHandleList:handleSubmit',
            name: '提交（办理页面）',
            method: 'POST',
            type: 'btn',
            description: '提交（办理页面）',
            uri: '/awp/task/process/launch/conventional',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005018,
            code: 'archiveTaskHandleList:handleUpload',
            name: '添加文档（办理页面）',
            method: 'POST',
            type: 'btn',
            description: '添加文档（办理页面）',
            uri: '/awp/task/process/uploadFile',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005019,
            code: 'archiveTaskHandleList:updatecommit',
            name: '提交（发起任务页面）',
            method: 'POST',
            type: 'btn',
            description: '提交（发起任务页面）',
            uri: '/awp/task/commit',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005020,
            code: 'archiveTaskHandleList:uploadPrintingSubmit',
            name: '提交（用印文件归档的办理页面）',
            method: 'POST',
            type: 'btn',
            description: '提交（用印文件归档的办理页面）',
            uri: '/awp/task/process/launch/archive',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005021,
            code: 'archiveTaskHandleList:projectReport',
            name: '项目任务',
            method: 'POST',
            type: 'btn',
            description: '项目任务',
            uri: '/awp/task/list',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137005022,
            code: 'archiveTaskHandleList:seriesReport',
            name: '系列任务',
            method: 'POST',
            type: 'btn',
            description: '系列任务',
            uri: '/awp/task/list',
            uriFlag: '/yss-awp-server',
          },
        ],
      },
      {
        id: 137006,
        code: 'seriesManage',
        path: 'projectManagement/seriesManage',
        name: '项目系列管理',
        title: '项目系列管理',
        icon: '',
        href: '',
        description: '',
        actions: [
          // {
          //   id: 137006001,
          //   code: 'seriesManage:query',
          //   name: '项目系列管理:主表格查询',
          //   method: 'POST',
          //   type: 'btn',
          //   description: '项目系列管理:主表格查询',
          //   uri: '/product/getProductPage',
          //   uriFlag: '/yss-awp-server',
          // },
          {
            id: 137006002,
            code: 'seriesManage:add',
            name: '新建系列',
            method: 'POST',
            type: 'btn',
            description: '项目系列管理新建系列',
            uri: '/product/addProduct',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137006003,
            code: 'seriesManage:look',
            name: '查看',
            method: 'POST',
            type: 'btn',
            description: '项目系列管理查看系列信息',
            uri: '/product/updateProductNew',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137006004,
            code: 'seriesManage:deCheck',
            name: '反审核',
            method: 'POST',
            type: 'btn',
            description: '项目系列管理反审核',
            uri: '/product/batchCheckProduct',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137006005,
            code: 'seriesManage:check',
            name: '审核',
            method: 'POST',
            type: 'btn',
            description: '项目系列管理审核',
            uri: '/product/batchCheckProduct',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137006006,
            code: 'seriesManage:update',
            name: '修改',
            method: 'POST',
            type: 'btn',
            description: '项目系列管理修改',
            uri: '/product/updateProductNew',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137006007,
            code: 'seriesManage:delete',
            name: '删除',
            method: 'POST',
            type: 'btn',
            description: '项目系列管理删除',
            uri: '/product/batchDeleteProduct',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 137006008,
            code: 'seriesManage:stop',
            name: '终止',
            method: 'POST',
            type: 'btn',
            description: '项目系列管理终止',
            uri: '/product/terminationProduct',
            uriFlag: '/yss-awp-server',
          },
          // {
          //   id: 137006011,
          //   code: 'seriesManage:saveUrl',
          //   name: '新建系列保存',
          //   method: 'POST',
          //   type: 'uri',
          //   description: '新建系列保存',
          //   uri: '/product/addProduct',
          //   uriFlag: '/yss-awp-server',
          // },
          {
            id: 137006012,
            code: 'seriesManage:apply',
            name: '申报',
            method: 'POST',
            type: 'btn',
            description: '项目系列管理申报',
            uri: '/product/projectReport',
            uriFlag: '/yss-awp-server',
          },
        ],
      },
    ],
  },
  {
    id: 138,
    code: 'manuscriptSystem',
    name: '底稿目录管理',
    title: '底稿目录管理',
    children: [
      {
        id: 138001,
        code: 'manuscriptBasic',
        path: 'manuscriptSystem/manuscriptBasic',
        name: '底稿标准目录配置',
        title: '底稿标准目录配置',
        icon: '',
        href: '',
        description: '',
        actions: [
          {
            id: 138001001,
            code: 'manuscriptBasic:query',
            name: '底稿标准目录配置表格查询',
            method: 'POST',
            type: 'btn',
            description: '底稿标准目录配置表格查询',
            uri: '/commonPath/getPathList',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138001002,
            code: 'manuscriptBasic:add',
            name: '新增',
            method: 'POST',
            type: 'uri',
            description: '新增',
            uri: '/manuscriptBasic/manuscriptBasicSov',
            uriFlag: '/manuscriptSystem',
          },
          {
            id: 138001003,
            code: 'manuscriptBasic:check',
            name: '查看',
            method: 'POST',
            type: 'uri',
            description: '查看',
            uri: '/manuscriptBasic/manuscriptBasicSov',
            uriFlag: '/manuscriptSystem',
          },
          {
            id: 138001004,
            code: 'manuscriptBasic:audit',
            name: '审核',
            method: 'GET',
            type: 'btn',
            description: '审核',
            uri: '/commonPath/checked',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138001005,
            code: 'manuscriptBasic:reAudit',
            name: '反审核',
            method: 'GET',
            type: 'btn',
            description: '反审核',
            uri: '/commonPath/checked',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138001006,
            code: 'manuscriptBasic:treeDelete',
            name: '删除',
            method: 'POST',
            type: 'btn',
            description: '删除',
            uri: '/commonPath/delete',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138001007,
            code: 'manuscriptBasic:treeUpdate',
            name: '修改',
            method: 'POST',
            type: 'btn',
            description: '修改',
            uri: '/commonPath/edit',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138001008,
            code: 'manuscriptBasic:treeAdd',
            name: '添加',
            method: 'POST',
            type: 'btn',
            description: '添加',
            uri: '/commonPath/add',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138001009,
            code: 'manuscriptBasic:cancel',
            name: '取消',
            method: 'POST',
            type: 'uri',
            description: '取消',
            uri: '/manuscriptBasic',
            uriFlag: '/manuscriptSystem',
          },
        ],
      },
      {
        id: 138002,
        code: 'manuscriptManage',
        path: 'manuscriptSystem/manuscriptManage',
        name: '项目底稿目录管理',
        title: '项目底稿目录管理',
        icon: '',
        href: '',
        description: '',
        actions: [
          {
            id: 138002001,
            code: 'manuscriptManage:query',
            name: '项目底稿目录管理表格查询',
            method: 'POST',
            type: 'btn',
            description: '项目底稿目录管理表格查询',
            uri: '/product/getProductPage',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138002002,
            code: 'manuscriptManage:check',
            name: '查看',
            method: 'POST',
            type: 'uri',
            description: '查看',
            uri: '/manuscriptManageDetail',
            uriFlag: '/manuscriptSystem',
          },
          {
            id: 138002003,
            code: 'manuscriptManage:audit',
            name: '审核',
            method: 'GET',
            type: 'btn',
            description: '审核',
            uri: '/path/checked',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138002004,
            code: 'manuscriptManage:reAudit',
            name: '反审核',
            method: 'GET',
            type: 'btn',
            description: '反审核',
            uri: '/path/checked',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138002005,
            code: 'manuscriptManage:treeDelete',
            name: '删除',
            method: 'POST',
            type: 'btn',
            description: '删除',
            uri: '/commonPath/delete',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138002006,
            code: 'manuscriptManage:treeUpdate',
            name: '修改',
            method: 'POST',
            type: 'btn',
            description: '修改',
            uri: '/commonPath/edit',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138002007,
            code: 'manuscriptManage:treeAdd',
            name: '添加',
            method: 'POST',
            type: 'btn',
            description: '添加',
            uri: '/commonPath/add',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138002008,
            code: 'manuscriptManage:treeApply',
            name: '不适用',
            method: 'POST',
            type: 'btn',
            description: '不适用',
            uri: '/path/setPath',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138002009,
            code: 'manuscriptManage:treeRevApply',
            name: '不适用修改',
            method: 'GET',
            type: 'btn',
            description: '不适用修改',
            uri: '/path/getNoPathTree',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138002010,
            code: 'manuscriptManage:cancel',
            name: '取消',
            method: 'POST',
            type: 'uri',
            description: '取消',
            uri: '/manuscriptManage',
            uriFlag: '/manuscriptSystem',
          },
        ],
      },
      {
        id: 138003,
        code: 'manuscriptManagement',
        path: 'manuscriptSystem/manuscriptManagement',
        name: '项目电子底稿管理',
        title: '项目电子底稿管理',
        icon: '',
        href: '',
        description: '',
        actions: [
          // {
          //   id: 138003001,
          //   code: 'manuscriptManagement:query',
          //   name: '项目底稿列表查询',
          //   method: 'POST',
          //   type: 'btn',
          //   description: '项目底稿列表查询',
          //   uri: '/product/getQueryParamList',
          //   uriFlag: '/yss-awp-server',
          // },
          {
            id: 138003002,
            code: 'manuscriptManagement:viewPage',
            name: '查看底稿',
            method: 'POST',
            type: 'btn',
            description: '查看底稿',
            uri: 'productFile/getFileDetailList',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138003003,
            code: 'manuscriptManagement:changeLog',
            name: '变更记录',
            method: 'POST',
            type: 'btn',
            description: '变更记录',
            uri: '/product/getProductPageChecked',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138003004,
            code: 'manuscriptManagement:selectSubmit',
            name: '选择报送',
            method: 'POST',
            type: 'uri',
            description: '选择报送',
            uri: '',
            uriFlag: '',
          },
          // {
          //   id: 138003005,
          //   code: 'manuscriptManagement:fileSubmission',
          //   name: '项目电子底稿管理:选择报送:文件报送',
          //   method: 'POST',
          //   type: 'btn',
          //   description: '项目电子底稿管理:选择报送:文件报送',
          //   uri: '/remote/wpFileUpload',
          //   uriFlag: '/yss-awp-server',
          // },
          // {
          //   id: 138003006,
          //   code: 'manuscriptManagement:spotCheckSubmission',
          //   name: '项目电子底稿管理:选择报送:抽查报送',
          //   method: 'POST',
          //   type: 'btn',
          //   description: '项目电子底稿管理:选择报送:抽查报送',
          //   uri: '/path/getSysTree',
          //   uriFlag: '/yss-awp-server',
          // },
          // {
          //   id: 138003007,
          //   code: 'manuscriptManagement:peopleSubmission',
          //   name: '项目电子底稿管理:选择报送:人员报送',
          //   method: 'POST',
          //   type: 'btn',
          //   description: '项目电子底稿管理:选择报送:人员报送',
          //   uri: '/remote/wpItemUpdate',
          //   uriFlag: '/yss-awp-server',
          // },
          {
            id: 138003008,
            code: 'manuscriptManagement:projectDirectory',
            name: '项目目录',
            method: 'POST',
            type: 'btn',
            description: '项目目录',
            uri: '/product/getProductPageChecked',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138003009,
            code: 'manuscriptManagement:seriesDirectory',
            name: '系列目录',
            method: 'POST',
            type: 'btn',
            description: '系列目录',
            uri: '/product/getProductPageChecked',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138003010,
            code: 'manuscriptManagement:detailUpdateFile',
            name: '更新',
            method: 'POST',
            type: 'btn',
            description: '更新',
            uri: '/awp/updateUseSealFile',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138003012,
            code: 'manuscriptManagement:updateHandle',
            name: '更新',
            method: 'POST',
            type: 'btn',
            description: '更新',
            uri: '/task/fileUpdate/updateHandle',
            uriFlag: '/yss-awp-server',
          },
        ],
      },
      {
        id: 138004,
        code: 'manuscriptManagementReportResult',
        path: 'manuscriptSystem/manuscriptManagementReportResult',
        name: '项目底稿报送查询',
        title: '项目底稿报送查询',
        icon: '',
        href: '',
        description: '',
        actions: [
          // {
          //   id: 138004001,
          //   code: 'manuscriptManagementReportResultMasterTable:query',
          //   name: '报送结果主列表查询',
          //   method: 'POST',
          //   type: 'btn',
          //   description: '报送结果主列表查询',
          //   uri: '/remote/remoteLogsMaster',
          //   uriFlag: '/yss-awp-server',
          // },
          {
            id: 138004002,
            code: 'manuscriptManagementReportResultSubTable:query',
            name: '报送结果子列表查询',
            method: 'POST',
            type: 'btn',
            description: '报送结果子列表查询',
            uri: '/remote/remoteLogsSub',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138004003,
            code: 'manuscriptManagementReportResult:projectReport',
            name: '项目报送',
            method: 'POST',
            type: 'btn',
            description: '项目报送',
            uri: '/remote/remoteLogsMaster',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 138004004,
            code: 'manuscriptManagementReportResult:seriesReport',
            name: '系列报送',
            method: 'POST',
            type: 'btn',
            description: '系列报送',
            uri: '/remote/remoteLogsMaster',
            uriFlag: '/yss-awp-server',
          },
        ],
      },
    ],
  },
  {
    id: 140,
    code: 'manuscriptManagementOperationLog',
    name: '底稿日志管理',
    title: '底稿日志管理',
    children: [
      {
        id: 140001,
        code: 'manuscriptManagementOperationLogIndex',
        path: 'manuscriptManagementOperationLog/manuscriptManagementOperationLogIndex',
        name: '底稿日志查询',
        title: '底稿日志查询',
        icon: '',
        href: '',
        description: '',
        actions: [
          // {
          //   id: 140001001,
          //   code: 'manuscriptManagementOperationLogIndex:query',
          //   name: '操作日志首页列表',
          //   method: 'POST',
          //   type: 'btn',
          //   description: '操作日志首页列表',
          //   uri: '/product/getQueryParamList',
          //   uriFlag: '/yss-awp-server',
          // },
          {
            id: 140001002,
            code: 'manuscriptManagementOperationLogIndex:viewPage',
            name: '查看',
            method: 'POST',
            type: 'btn',
            description: '查看',
            uri: '/tAwpLog/list',
            uriFlag: '/yss-awp-server',
          },
          {
            id: 140001003,
            code: 'manuscriptManagementOperationLogIndex:relatedLogs',
            name: '项目相关日志',
            method: 'POST',
            type: 'btn',
            description: '项目相关日志',
            uri: '/product/getProductPageChecked',
            uriFlag: '/yss-awp-server',
          },
          // {
          //   id: 140001004,
          //   code: 'manuscriptManagementOperationLogIndex:noRelatedLogs',
          //   name: '底稿日志查询:非项目相关日志',
          //   method: 'POST',
          //   type: 'btn',
          //   description: '底稿日志查询:非项目相关日志',
          //   uri: '/tAwpLog/list',
          //   uriFlag: '/yss-awp-server',
          // },
        ],
      },
    ],
  },
];

export default manuscriptResources;
