// 多路校验
const multipleCheckBasicResources = [
  {
    id: 101,
    code: 'systemSetings',
    title: '系统设置',
    icon: 'tool',
    name: '系统设置',
    href: '',
    description: '',
    children: [
      {
        id: 101007,
        code: 'dataSourceConfig',
        path: '/multipleCheck/systemSetings/dataSourceConfig',
        title: '数据源管理',
        icon: '',
        name: '数据源管理',
        href: '/com/yss/datamiddle/controller',
        description: '',
        actions: [
          {
            id: 101005001,
            code: 'dataSourceConfig:query',
            name: '查询',
            method: 'POST',
            type: 'btn',
            description: '查询',
            uri: '/dateCenter/uery',
            uriFlag: '/yss-date-center',
          },
        ],
      },
      {
        id: 101006,
        code: 'sourceTable',
        path: '/multipleCheck/systemSetings/sourceTableList',
        title: '数据源表信息管理',
        icon: '',
        name: '数据源表信息管理',
        href: '/com/yss/datamiddle/controller',
        description: '',
        actions: [
          {
            id: 101006001,
            code: 'sourceTable:query',
            name: '查询',
            method: 'POST',
            type: 'btn',
            description: '查询',
            uri: '/dateCenter/uery',
            uriFlag: '/yss-date-center',
          },
        ],
      },
      {
        id: 101007,
        code: 'tableCategory',
        path: '/multipleCheck/systemSetings/tableCategory',
        title: '表分类管理',
        icon: '',
        name: '表分类管理',
        href: '/com/yss/datamiddle/controller',
        description: '',
        actions: [
          {
            id: 101007001,
            code: 'tableCategory:query',
            name: '查询',
            method: 'POST',
            type: 'btn',
            description: '查询',
            uri: '/dateCenter/uery',
            uriFlag: '/yss-date-center',
          },
        ],
      },
      {
        id: 101008,
        code: 'pTableRules',
        href: '/com/yss/datamiddle/controller',
        title: '表校验规则配置',
        icon: '',
        name: '表校验规则配置',
        path: '/multipleCheck/systemSetings/pTableRules',
        description: '',
        actions: [
          {
            id: 101008001,
            code: 'pTableRules:query',
            name: '查询',
            method: 'POST',
            type: 'btn',
            description: '查询',
            uri: '/dateCenter/uery',
            uriFlag: '/yss-date-center',
          },
        ],
      },
      {
        id: 101009,
        code: 'executeRules',
        href: '/com/yss/datamiddle/controller',
        title: '调度方案配置',
        icon: '',
        name: '调度方案配置',
        path: '/multipleCheck/systemSetings/executeRules',
        description: '',
        actions: [
          {
            id: 101009001,
            code: 'executeRules:query',
            name: '查询',
            method: 'POST',
            type: 'btn',
            description: '查询',
            uri: '/dateCenter/uery',
            uriFlag: '/yss-date-center',
          },
        ],
      },
      {
        id: 101010,
        code: 'taskVerification',
        href: '/com/yss/datamiddle/controller',
        title: '校验任务配置',
        icon: '',
        name: '校验任务配置',
        path: '/multipleCheck/systemSetings/taskVerification',
        description: '',
        actions: [
          {
            id: 101010001,
            code: 'taskVerification:query',
            name: '查询',
            method: 'POST',
            type: 'btn',
            description: '查询',
            uri: '/dateCenter/uery',
            uriFlag: '/yss-date-center',
          },
        ],
      },
    ],
    actions: [],
    path: '',
  },
  {
    id: 102,
    code: 'dataReport',
    title: '数据校验',
    icon: 'tool',
    name: '数据校验',
    href: '',
    description: 'dataReport',
    children: [
      {
        id: 102007,
        code: 'datamiddle',
        href: '/com/yss/datamiddle/controller',
        title: '校验监控',
        icon: '',
        name: '校验监控',
        path: '/multipleCheck/dataReport/process',
        description: '',
        actions: [
          {
            id: 104007001,
            code: 'datamiddle:query',
            name: '查询',
            method: 'POST',
            type: 'btn',
            description: '查询',
            uri: '/dateCenter/uery',
            uriFlag: '/yss-date-center',
          },
        ],
      },
      {
        id: 102008,
        code: 'checkReport',
        href: '/com/yss/datamiddle/controller',
        title: '校验报告',
        icon: '',
        name: '校验报告',
        path: '/multipleCheck/dataReport/checkReport',
        description: '校验报告',
        actions: [
          {
            id: 102008001,
            code: 'checkReport:query',
            name: '查询',
            method: 'POST',
            type: 'btn',
            description: '查询',
            uri: '/dateCenter/uery',
            uriFlag: '/yss-date-center',
          },
        ],
      },
      {
        id: 102009,
        code: 'checkDiff',
        href: '/com/yss/datamiddle/controller',
        title: '差异处理',
        icon: '',
        name: '差异处理',
        path: '/multipleCheck/dataReport/checkDiff',
        description: '差异处理',
        actions: [
          {
            id: 102009001,
            code: 'checkDiff:query',
            name: '查询',
            method: 'POST',
            type: 'btn',
            description: '查询',
            uri: '/dateCenter/uery',
            uriFlag: '/yss-date-center',
          },
        ],
      },
    ],
    actions: [],
    path: '',
  },
  {
    id: 103,
    code: 'quality',
    title: '质量统计',
    icon: 'tool',
    name: '质量统计',
    href: '',
    description: '质量统计',
    children: [
      {
        id: 103007,
        code: 'dataAccidentInfo',
        href: '/com/yss/datamiddle/controller',
        title: '数据事故明细',
        icon: '',
        name: '数据事故明细',
        path: '/multipleCheck/quality/dataAccidentInfo',
        description: '数据事故明细',
        actions: [
          {
            id: 103007001,
            code: 'dataAccidentInfo:query',
            name: '查询',
            method: 'POST',
            type: 'btn',
            description: '查询',
            uri: '/dateCenter/uery',
            uriFlag: '/yss-date-center',
          },
        ],
      },
      {
        id: 103008,
        code: 'dataAccident',
        href: '/com/yss/datamiddle/controller',
        title: '数据事故统计',
        icon: '',
        name: '数据事故统计',
        path: '/multipleCheck/quality/dataAccident',
        description: '数据事故统计',
        actions: [
          {
            id: 103008001,
            code: 'dataAccident:query',
            name: '查询',
            method: 'POST',
            type: 'btn',
            description: '查询',
            uri: '/dateCenter/uery',
            uriFlag: '/yss-date-center',
          },
        ],
      },
    ],
    actions: [],
    path: '',
  },
  {
    id: 104,
    code: 'logs',
    title: '日志记录',
    icon: 'tool',
    name: '日志记录',
    href: '',
    description: '日志记录',
    children: [
      {
        id: 104007,
        code: 'runningLog',
        href: '/com/yss/datamiddle/controller',
        title: '任务运行日志',
        icon: '',
        name: '任务运行日志',
        path: '/multipleCheck/log/runningLog',
        description: '任务运行日志',
        actions: [
          {
            id: 104007001,
            code: 'runningLog:query',
            name: '查询',
            method: 'POST',
            type: 'btn',
            description: '查询',
            uri: '/dateCenter/uery',
            uriFlag: '/yss-date-center',
          },
        ],
      },
    ],
    actions: [],
    path: '',
  },
];

export default multipleCheckBasicResources;
