// 调度
const SchedulingResources = [
  {
    code: 'dashboard',
    id: 101,
    name: '调度仪表盘',
    icon: 'flag',
    title: '调度仪表盘',
    href: '',
    children: [
      {
        code: 'home',
        id: 101001,
        name: '调度仪表盘',
        path: '/dispatch/home',
        icon: 'flag',
        title: '调度仪表盘',
        href: '',
        actions: [
          {
            id: 101001001,
            code: 'dashboard:actions',
            name: '调度仪表盘',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
    ],
  },
  {
    code: 'projects',
    id: 102,
    name: '项目管理',
    icon: 'flag',
    title: '项目管理',
    href: '',
    children: [
      {
        code: 'projectsList',
        id: 102001,
        name: '项目管理',
        path: '/dispatch/projects/list',
        icon: 'flag',
        title: '项目管理',
        href: '',
        actions: [
          {
            id: 102001001,
            code: 'projects:actions',
            name: '文件管理',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
    ],
  },
  {
    code: 'resource',
    id: 103,
    name: '资源中心',
    icon: 'flag',
    title: '资源中心',
    href: '',
    children: [
      {
        code: 'file',
        id: 103101,
        name: '文件管理',
        path: '/dispatch/resource/file',
        icon: '',
        title: '文件管理',
        href: '',
        actions: [
          {
            id: 103001001,
            code: 'resource:file',
            name: '文件管理',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
      {
        code: 'calendar',
        id: 103102,
        name: '调度日历管理',
        path: '/dispatch/resource/calendar',
        icon: '',
        title: '调度日历管理',
        href: '',
        actions: [
          {
            id: 103002001,
            code: 'resource:calendar',
            name: '调度日历管理',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
      {
        code: 'platform',
        id: 103103,
        name: '第三方平台管理',
        path: '/dispatch/resource/platform',
        icon: '',
        title: '第三方平台管理',
        href: '',
        actions: [
          {
            id: 103003001,
            code: 'resource:platform',
            name: '第三方平台管理',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
      {
        code: 'udf',
        id: 103104,
        name: 'UDF资源管理',
        path: '/dispatch/resource/udf',
        icon: '',
        title: 'UDF资源管理',
        href: '',
        actions: [
          {
            id: 103004001,
            code: 'resource:udf',
            name: 'UDF资源管理',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
      {
        code: 'func',
        id: 103105,
        name: 'UDF函数管理',
        path: '/dispatch/resource/func',
        icon: '',
        title: 'UDF函数管理',
        href: '',
        actions: [
          {
            id: 103005001,
            code: 'resource:func',
            name: 'UDF函数管理',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
    ],
  },
  {
    code: 'datasource',
    id: 104,
    name: '数据源中心',
    icon: 'flag',
    title: '数据源中心',
    href: '',
    children: [
      {
        code: 'datasourceDatasource',
        id: 104001,
        name: '数据源中心',
        path: '/dispatch/datasource/list',
        icon: 'flag',
        title: '数据源中心',
        href: '',
        actions: [
          {
            id: 104001001,
            code: 'datasource:actions',
            name: '数据源中心',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
    ],
  },
  {
    code: 'monitor',
    id: 105,
    name: '监控中心',
    icon: 'flag',
    title: '监控中心',
    href: '',
    children: [
      {
        code: 'master',
        id: 105001,
        name: 'Master',
        path: '/dispatch/monitor/servers/master',
        icon: '',
        title: 'Master',
        href: '',
        actions: [
          {
            id: 105001001,
            code: 'monitor:master',
            name: 'Master',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
      {
        code: 'worker',
        id: 105002,
        name: 'Worker',
        path: '/dispatch/monitor/servers/worker',
        icon: '',
        title: 'Worker',
        href: '',
        actions: [
          {
            id: 105002001,
            code: 'monitor:worker',
            name: 'Worker',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
      {
        code: 'zookeeper',
        id: 105003,
        name: 'Zookeeper',
        path: '/dispatch/monitor/servers/zookeeper',
        icon: '',
        title: 'Zookeeper',
        href: '',
        actions: [
          {
            id: 105003001,
            code: 'monitor:zookeeper',
            name: 'Zookeeper',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
      {
        code: 'db',
        id: 105004,
        name: 'DB',
        path: '/dispatch/monitor/servers/db',
        icon: '',
        title: 'DB',
        href: '',
        actions: [
          {
            id: 105004001,
            code: 'monitor:db',
            name: 'DB',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
      {
        code: 'statistics',
        id: 105005,
        name: 'Statistics',
        path: '/dispatch/monitor/servers/statistics',
        icon: '',
        title: 'Statistics',
        href: '',
        actions: [
          {
            id: 105005001,
            code: 'monitor:statistics',
            name: 'Statistics',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
    ],
  },
  {
    code: 'security',
    id: 106,
    name: '安全中心',
    icon: 'flag',
    title: '安全中心',
    href: '',
    children: [
      {
        code: 'tenant',
        id: 106001,
        name: '租户管理',
        path: '/dispatch/security/tenant',
        icon: '',
        title: '租户管理',
        href: '',
        actions: [
          {
            id: 106005001,
            code: 'security:tenant',
            name: '租户管理',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
      {
        code: 'users',
        id: 106002,
        name: '用户管理',
        path: '/dispatch/security/users',
        icon: '',
        title: '用户管理',
        href: '',
        actions: [
          {
            id: 106002001,
            code: 'security:users',
            name: '用户管理',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
      {
        code: 'warning-groups',
        id: 106003,
        name: '告警组管理',
        path: '/dispatch/security/warning-groups',
        icon: '',
        title: '告警组管理',
        href: '',
        actions: [
          {
            id: 106003001,
            code: 'security:warning-groups',
            name: '告警组管理',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
      {
        code: 'worker-groups',
        id: 106004,
        name: 'Worker分组管理',
        path: '/dispatch/security/worker-groups',
        icon: '',
        title: 'Worker分组管理',
        href: '',
        actions: [
          {
            id: 106004001,
            code: 'security:worker-groups',
            name: 'Worker分组管理',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
      {
        code: 'queue',
        id: 106005,
        name: '队列管理',
        path: '/dispatch/security/queue',
        icon: '',
        title: '队列管理',
        href: '',
        actions: [
          {
            id: 106005001,
            code: 'security:queue',
            name: '队列管理',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
      {
        code: 'token',
        id: 106006,
        name: '令牌管理',
        path: '/dispatch/security/token',
        icon: '',
        title: '令牌管理',
        href: '',
        actions: [
          {
            id: 106006001,
            code: 'security:token',
            name: '令牌管理',
            method: 'DELETE',
            type: 'btn',
            tabUri: '///',
            description: '',
            uri: '/user/del/{$id}',
            uriFlag: '/yss-base-admin',
          },
        ],
      },
    ],
  },
];

export default SchedulingResources;
